language: python
sudo: false
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
install:
  - pip install -q Django==$DJANGO
script:
  - DJANGO_SETTINGS_MODULE=tests.settings python setup.py test

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7

    - python: "2.6"
      env: DJANGO=1.8

    - python: "2.6"
      env: DJANGO=1.9

    - python: "2.6"
      env: DJANGO=1.10
