language: python
python:
  - "2.6"
  - "2.7"
env:
#  - DJANGO=1.2
#  - DJANGO=1.3
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
install:
  - pip install -q Django==$DJANGO
script:
  - python setup.py test
